# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.


url : https://serene-poitras-96eab5.netlify.com

# liquid debug
liquid:
  strict_variables: false # default: false
  strict_filters: true # default: false
  error_mode: strict # default: warn

# include debug
# sets html comment at include start and end
comment_includes: true

# loads netlify identity js if necessary on a non production branch
allow_netlify_identity: true
