---
# This file is processed by Jekyll
# Leave this front matter here !
---
##################################################################
# Netlify CMS configuration
# @see https://www.netlifycms.org/docs/add-to-your-site/
##################################################################

backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
  branch: dev # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: "img" # Media files will be stored in the repo under images/uploads

site_url: {{ site.url }}
display_url: {{ site.url }}
logo_url: {{ site.url }}/img/logo-musee-africart-kara-togo-kwele-optimized-omgsvg.svg
locale: {{ site.locale }}

show_preview_links: true

media_library:
  name: cloudinary
  output_filename_only: true
  config:
    cloud_name: {{ site.cloudinary.cloud_name }}
    api_key: {{ site.cloudinary.api_key }}

collections:

  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{% raw %}{{year}}-{{month}}-{{day}}-{{slug}}{% endraw %}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: false # prevents users from deleting items in a collection; defaults to true
    fields: # The fields for each document, usually in front matter
      - {label: "Titre", name: "title", widget: "string"}
      - {label: "Résumé", name: "excerpt", widget: "markdown"}
      - {label: "Texte", name: "body", widget: "markdown"}
#      - {label: "Catégories", name: "categories", widget: "categories"}
      - label: "Tags"
        name: "tags"
        hint: une liste de tags séparé par une virgule (tag1, tag2, un autre tag)
        widget: "list"
        default: [""]
        required: false

{% include cms-admin/header.yml %}
{% include cms-admin/features.yml %}
{% include cms-admin/gallery.yml %}

{% comment %} +++++++++++++++++++++++++++++++++++++++++++++++++++++
Uses default Jekyll's config to set default values
when we create a new item
+++++++++++++++++++++++++++++++++++++++++++++++++++++{% endcomment %}
{% assign default_conf = site.defaults | where_exp: "def", "def.scope.type == 'pages'" | first %}
{% assign default_values = default_conf.values %}

  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{% raw %}{{slug}}{% endraw %}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: true # prevents users from deleting items in a collection; defaults to true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Body"
        name: "body"
        widget: "markdown"

      - label: "Sitemap"
        name: "sitemap"
        widget: "boolean"
        default: false

      - label: "Permalink"
        name: "permalink"
        widget: "string"
        required: false

      - label: "Layout"
        name: "layout"
        widget: "string"
        default: "{{ default_values.layout }}"
        required: false

      - label: "Classes"
        name: "classes"
        widget: "string"
        default: "{{ default_values.classes }}"
        required: false

{% comment %}{% endcomment %}
{% include cms-admin/header.yml %}
{% include cms-admin/features.yml %}
{% include cms-admin/gallery.yml %}


  - name: "categories" # Used in routes, e.g., /admin/collections/blog
    label: "Catégories" # Used in the UI
    folder: "_categories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{% raw %}{{slug}}{% endraw %}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: true # prevents users from deleting items in a collection; defaults to true
    fields: # The fields for each document, usually in front matter
      - { label: "Titre", name: "title", widget: "string"}
      - { label: Nom, name: name, widget: string, hint: "Fêtes traditionelles - Nom: fetes-traditionnelles" }
      - { label: Description, name: description, widget: markdown, required: false }
