---
---
##################################################################
# Netlify CMS configuration
# @see https://www.netlifycms.org/docs/add-to-your-site/
##################################################################

backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
    - admin
    - editor
  branch: master # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: "img" # Media files will be stored in the repo under images/uploads

site_url: {{ site.url }}
display_url: {{ site.url }}
logo_url: {{ site.url }}/img/logo-musee-africart-kara-togo-kwele-optimized-omgsvg.svg

show_preview_links: true

collections:

  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    label_singular: "Blog" # Used in the UI for singular
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    delete: false # prevents users from deleting items in a collection; defaults to true
    extension: md
    format: frontmatter
    slug: "{{slug}}"
    fields: # The fields for each document, usually in front matter
      - name: "header"
        label: "header"
        widget: "string"
        required: false
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Published", name: "published", widget: "boolean", , default: true}
      - {label: "permalink", name: "permalink", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Featured Image", name: "thumbnail", widget: "image"}
      - {label: "Body", name: "body", widget: "markdown"}
      - label: "Tags"
        name: "tags"
        widget: "list"
        default: ["news"]
        required: false
