---
# This file is processed by Jekyll
# Leave this front matter here !
---
##################################################################
# Netlify CMS configuration
# @see https://www.netlifycms.org/docs/add-to-your-site/
##################################################################

backend:
  name: git-gateway
  accept_roles: #optional - accepts all users if left out
  branch: dev # Branch to update (optional; defaults to master)

# publish_mode: editorial_workflow

media_folder: "img" # Media files will be stored in the repo under images/uploads

site_url: {{ site.url }}
display_url: {{ site.url }}
logo_url: {{ site.url }}/img/logo-musee-africart-kara-togo-kwele-optimized-omgsvg.svg

show_preview_links: true

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: false # prevents users from deleting items in a collection; defaults to true
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Excerpt", name: "excerpt", widget: "markdown"}
      - {label: "Body", name: "body", widget: "markdown"}

      - label: "Tags"
        name: "tags"
        hint: une liste de tags séparé par une virgule (tag1, tag2, un autre tag)
        widget: "list"
        default: [""]
        required: false

      - label: "Header"
        name: "header"
        required: false
        widget: "object"
        fields:
          - {label: "Couleur de masque", name: overlay_color, widget: hidden, default: "#000"}
          - {label: "Transparence de masque", name: overlay_filter, widget: hidden, default: "0.5"}
          - {label: "Image", name: overlay_image, widget: image, default: false, required: false}
          - {label: "Caption", name: caption, widget: string, default: "", required: false}


  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    delete: false # prevents users from deleting items in a collection; defaults to true
    fields:
      - label: "Title"
        name: "title"
        widget: "string"

      - label: "Body"
        name: "body"
        widget: "markdown"

      - label: "Sitemap"
        name: "sitemap"
        widget: "boolean"
        default: false

      - label: "Permalink"
        name: "permalink"
        widget: "string"
        required: false

{% comment %}
{% include cms-admin/header.yml %}
{% endcomment %}

      - label: "Bloc de texte"
        name: "features"
        widget: "list"
        fields:

          - label: "Type"
            name: type
            hint: "left, center or right"
            widget: string
            default: "left"

          - label: "Image"
            name: image_path
            widget: image
            default: "{{ site.logo }}"
            required: false

          - label: "Texte image"
            name: image_caption
            widget: text
            default: "Image {{ site.title }}"
            required: false

          - label: "Text alternatif image"
            name: alt
            widget: text
            required: false

          - label: "Titre"
            name: title
            widget: text
            required: false

          - label: "Intro"
            name: excerpt
            widget: markdown
            required: false

          - label: "URL bouton"
            name: url
            widget: text
            required: false

          - label: "Texte bouton"
            name: btn_label
            widget: text
            required: false

          - label: "Style bouton"
            name: btn_class
            widget: text
            required: false


